### ISSUE TITLE
about the cleaning model

### ISSUE THREAD

**Issue by xilinniao123** [uds-lsv/noise-matrix-ner#1]
thanks for sharing! i want to ask about the cleaning model.
 in my opinion,if i use the trained cleaning model to predict the noise data, the  result(such as f1) is better than noise data origin lable? is  this right?
but my experiment show that after trained,the result is worse than noise orgin lable,have you experiment it?

**Comment by michael-aloys** [comment]
Hi,

just to make sure: You are asking about the cleaning model (adapted from Veit et al., 2017) not our noise matrix models, arent't you?

Your intuition is right, ideally, the predictions of the cleaning model applied on the noisy data should be better than the original noisy data.

If you look at our paper ( https://www.aclweb.org/anthology/D19-1362.pdf ), Table 1, you can see that for some, but not all, of the datasets, it actually performs worse than the baseline with noisy data but without cleaning (columns "De", "Es" and "Nl", comparing 2. and 3. row). That could indicate that the new labels obtained from the cleaning model are actually worse than the original labels. I do not have the specific analysis at hand if they are worse.

One reason could be that the cleaning model is not able to learn a good way of cleaning in this low-resource setting. The cleaning model is quite large compared to our proposed noise-matrix models, i.e. it needs to learn many weights. This might not be possible in the low-resource settings.

Things you could try out:
- The cleaning model originally uses Sigmoid on the last layer of the cleaning part. If you are also doing NER (or any other single-class classification, i.e. where you predict exactly one label per instance), you could try out replacing it with a softmax.
- Train the cleaning model with more data
- Use one of our approaches ;-)

One thing to keep in mind: Many noise modeling approaches do not create hard 0-1 labels. Instead they create soft-labels with probabilities when predicting cleaned or adapted versions of the labels. For the main-model/base-model, this shifted probability might be good for learning. So even if the labels are worse, when you convert them to hard 0-1 labels to evaluate with your standard F1-score, the soft-label version might still be useful for the main model as it indicates uncertainty.

I hope this could help you. If you have any other doubts, please, let me know.

**Comment by xilinniao123** [comment]
thanks for your answering
